src/modules/iotjs_module_udp.c

1. SetMulticastTTL and SetMulticastLoopback functions in UDP module
were enabled for TizenRT.
2. The updated libtuv supports TTL related features.
IoT.js-DCO-1.0-Signed-off-by: Piotr Marcinkiewicz p.marcinkiew@samsung.com

SetMulticastTTL, SetMulticastLoopback enabled in UDP for TizenRT

---

src/iotjs_string.c
src/modules/iotjs_module_buffer.c
test/testsets.json

libtuv expects cstrings while UDP module was passing javascript strings without terminator, which caused libtuv functions to fail
this fixes `test_dgram_address.js`

Workaround for string missing terminator

---

tools/check_test.js

The new option test-sets was introduced for check_test.js. It can be
used to execute only one or more sets of tests:
> iotjs tools/check_test.js test-sets=run_fail

Option to run specified test sets only

---

src/js/buffer.js
test/run_pass/issue/issue-1165.js
test/testsets.json

IoT.js-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com

Fix #1165 Buffer constructor is not passing encoding (#1204)

---

test/run_pass/test_net_connect.js

This fix closes the server in the test more clearly.

Fix test_net_connection (#1199)

---

test/run_pass/test_dgram_1_server_n_clients.js
test/run_pass/test_dgram_multicast_membership.js

- Be able to test server and client in one test app.
- Allow a single device to replace multiple clients by making delay

Change dgram test app (#1195)

---

tools/testrunner.py

This patch runs testsets in the order written in json. We can keep the test sequence we used so far with jsdriver.

Parse testsets json into ordered structure (#1206)

---

src/js/http_client.js
src/js/http_common.js
test/run_pass/test_fs_readdir.js

This patches the following possible errors found:
- Accessing properties without null check
- Use global variable without declaring it
- Loading unused modules

Fix possible errors in codes (#1221)

---

test/run_pass/test_fs_writefile_sync.js
tools/measure_coverage.sh
tools/testrunner.py

* Use the Python based testrunner to measure JavaScript coverage
IoT.js-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com
* Add argument parser to measure_coverage.sh to be more convenience
IoT.js-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com

Use the Python based testrunner to measure JavaScript coverage (#1196)

---

src/modules/iotjs_module_dns.c
src/modules/iotjs_module_tcp.c

IoT.js-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com

Fix memory leak on dns.getaddrinfo and tcp.onconnection (#1233)

---

config/tizenrt/artik05x/app/iotjs_main.c

SVACE error fix(160314)
IoT.js-DCO-1.0-Signed-off-by: Haesik, Jun haesik.jun@samsung.com

Fix static analysis error (#1235)

---

src/modules/iotjs_module_buffer.c
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_udp.c

Remove unnecessary variable declerations and IOTJS_UNUSED calls.

Code cleanup (#1293)

---

src/modules/iotjs_module_adc.c
src/modules/iotjs_module_blehcisocket.c
src/modules/iotjs_module_blehcisocket.h
src/modules/iotjs_module_fs.c
src/modules/iotjs_module_gpio.c
src/modules/iotjs_module_https.c
src/modules/iotjs_module_https.h
src/modules/iotjs_module_i2c.c
src/modules/iotjs_module_i2c.h
src/modules/iotjs_module_process.c
src/modules/iotjs_module_pwm.c
src/modules/iotjs_module_spi.c
src/modules/iotjs_module_stm32f4dis.c
src/modules/iotjs_module_stm32f4dis.h
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_tcp.h
src/modules/iotjs_module_testdriver.c
src/modules/iotjs_module_timer.c
src/modules/iotjs_module_timer.h
src/modules/iotjs_module_uart.c
src/modules/iotjs_module_udp.c
src/modules/iotjs_module_udp.h
src/platform/linux/iotjs_module_blehcisocket-linux.c
src/platform/linux/iotjs_module_gpio-linux.c
src/platform/nuttx/iotjs_module_stm32f4dis-nuttx.c

Change 'iotjs_jval_t*' function parameters and locals to 'iotjs_jval_t' under modules directory (part 2). 

Change 'iotjs_jval_t*' function parameters (#1213)

---

src/modules/iotjs_module_dns.c

SVACE error fix (160318)
Use of vulnerable function 'strcpy' at iotjs_module_dns.c
It's changed to 'strncpy'
IoT.js-DCO-1.0-Signed-off-by: Haesik, Jun haesik.jun@samsung.com

Fix static analysis error(160318) (#1237)

---

src/iotjs.c
src/iotjs_binding.c
src/iotjs_binding.h
src/modules/iotjs_module_buffer.c

Removed pointer from function parameter of 'iotjs_jval_get_global_object'. (#1227)

Removed pointer from function parameter (#1227)

---

src/iotjs_binding.c
src/iotjs_binding.h
src/modules/iotjs_module_fs.c
src/modules/iotjs_module_httpparser.c
src/modules/iotjs_module_process.c

Removed pointer from function parameter of 'iotjs_jval_set_property_by_index'. (#1239)

Removed pointer from function parameter (#1239)

---

src/modules/iotjs_module_process.c

When loading an external js file via require
the source code was duplicated internally to wrap
file contents into a function.
Using the jerry_parse_function method it is possible
to directly create the function from the source
without wrapping the source into a function.
IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

Avoid source string duplication during require (#1255)

---

tools/build.py

The js2c is not used in the build.py
thus we can remove it.
IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

Remove unused import from build.py (#1267)

---

src/iotjs_debuglog.c

This issue might also be present in libtuv/src/tuv_debuglog.c
IoT.js-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

Fix an issue causing stderr to close (#1268)

---

src/iotjs_binding.c
src/iotjs_binding.h

Moved all the necessary codes from the JHANDLER_CHECK into a
function to eliminate code duplications by using the macro.
IoT.js-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com

Use internal error handler function in the argument validator (#1256)

---

src/iotjs_binding_helper.c
src/iotjs_binding_helper.h
src/modules/iotjs_module_adc.c
src/modules/iotjs_module_dns.c
src/modules/iotjs_module_fs.c
src/modules/iotjs_module_gpio.c
src/modules/iotjs_module_httpparser.c
src/modules/iotjs_module_https.c
src/modules/iotjs_module_i2c.c
src/modules/iotjs_module_i2c.h
src/modules/iotjs_module_pwm.c
src/modules/iotjs_module_spi.c
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_tcp.h
src/modules/iotjs_module_timer.c
src/modules/iotjs_module_uart.c
src/modules/iotjs_module_udp.c

Removed pointer from function parameter of 'iotjs_make_callback' and 'iotjs_make_callback_with_result'. (#1260)

Removed pointer from function parameter (#1260)

---

src/iotjs_binding.c
src/iotjs_binding.h
src/iotjs_binding_helper.c
src/iotjs_module.c
src/modules/iotjs_module_adc.c
src/modules/iotjs_module_buffer.c
src/modules/iotjs_module_dns.c
src/modules/iotjs_module_fs.c
src/modules/iotjs_module_gpio.c
src/modules/iotjs_module_httpparser.c
src/modules/iotjs_module_i2c.c
src/modules/iotjs_module_process.c
src/modules/iotjs_module_pwm.c
src/modules/iotjs_module_spi.c
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_uart.c
src/modules/iotjs_module_udp.c

Removed 'iotjs_jval_t' pointer from 'iotjs_jval_get_undefined', 'iotjs_jval_get_null' and 'iotjs_jval_get_boolean'.

Removed 'iotjs_jval_t' pointer (#1261)

---

src/iotjs_handlewrap.c
src/iotjs_objectwrap.c
src/iotjs_objectwrap.h
src/iotjs_reqwrap.c
src/iotjs_reqwrap.h
src/modules/iotjs_module_adc.c
src/modules/iotjs_module_blehcisocket.c
src/modules/iotjs_module_blehcisocket.h
src/modules/iotjs_module_buffer.c
src/modules/iotjs_module_dns.c
src/modules/iotjs_module_fs.c
src/modules/iotjs_module_gpio.c
src/modules/iotjs_module_httpparser.c
src/modules/iotjs_module_i2c.c
src/modules/iotjs_module_i2c.h
src/modules/iotjs_module_pwm.c
src/modules/iotjs_module_spi.c
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_tcp.h
src/modules/iotjs_module_uart.c
src/modules/iotjs_module_udp.c

Removed 'iotjs_jval_t' pointer from 'iotjs_reqwrap' and 'iotjs_objectwrap'.

Removed 'iotjs_jval_t' pointer (#1271)

---

src/modules/iotjs_module_https.c

This patch is related to #1201 and changes some iotjs_jval_t* occurrences in https.

Remove uses of 'iotjs_jval_t' pointer from https (#1279)

---

src/platform/linux/iotjs_module_gpio-linux.c
src/platform/tizen/iotjs_module_gpio-tizen.c
src/platform/tizenrt/iotjs_module_gpio-tizenrt.c

changed for code consistency
reflect the comment of glistening in #1280

Replace iotjs_buffer_release to IOTJS_RELEASE (#1281)

---

src/iotjs_binding.h
src/modules/iotjs_module_blehcisocket.c
src/modules/iotjs_module_gpio.c
src/modules/iotjs_module_httpparser.c
src/modules/iotjs_module_i2c.c
src/modules/iotjs_module_process.c
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_udp.c

This check does not make any sense, because it will always be true,
due to using unsigned integer types.

Remove 'DJHANDLER_CHECK_ARGS(0)' calls. (#1289)

---

src/iotjs.c
src/iotjs_binding.c
src/iotjs_binding.h
src/iotjs_binding_helper.c
src/iotjs_module.c
src/iotjs_objectwrap.c
src/iotjs_reqwrap.c
src/modules/iotjs_module_adc.c
src/modules/iotjs_module_blehcisocket.c
src/modules/iotjs_module_buffer.c
src/modules/iotjs_module_fs.c
src/modules/iotjs_module_httpparser.c
src/modules/iotjs_module_https.c
src/modules/iotjs_module_i2c.c
src/modules/iotjs_module_pwm.c
src/modules/iotjs_module_spi.c
src/modules/iotjs_module_tcp.c
src/modules/iotjs_module_testdriver.c
src/modules/iotjs_module_timer.c
src/modules/iotjs_module_uart.c
src/modules/iotjs_module_udp.c
src/platform/linux/iotjs_module_blehcisocket-linux.c
src/platform/linux/iotjs_module_gpio-linux.c

* Removed 'iotjs_jval_is_*' functions
* Removed 'iotjs_error_t'
* Removed 'iotjs_binding_initialize' and 'iotjs_binding_finalize'

Simplify the binding layer. (#1290)

---

src/js/util.js
test/run_pass/test_console.js

In the case of `console.log({ a: '123', b: 123, c: [1, 2, 3]});`, the printed log is like the following:
Current:
[object Object]
This patch:
{"a":"123","b":123,"c":[1,2,3]}

Stringify object in console module (#1298)
