pmarcinkiew/iotjs

- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_tcp.h
- src/modules/iotjs_module_udp.c
> Optimize localhost to ip lookups

- config/romfs.def
- tools/precommit.py
romfs should (does it really?) work for Krzysztof for testing purposes
> Rework of romfs definition file and handling logic.

- src/js/module.js
- test/testsets.json
> Fix path handling when loading modules on TizenRT

- test/testsets.json
IoT.js-DCO-1.0-Signed-off-by: Piotr Marcinkiewicz p.marcinkiew@samsung.com
> test_iotjs_syntax_error.js enabled for TizenRT

- src/iotjs_string.c
> Change 0 pointer to cstring terminator in string logic

- tools/precommit.py
> Parser options: --skipbuild for artik053 & default for romfs

- src/modules/iotjs_module_udp.c
- src/modules/iotjs_module_udp.h
> Fix UDP buffer data destroy before send

- test/run_pass/test_dgram_setttl_server.js
> Fix server double close in dgram ttl tests

- test/run_pass/test_dgram_broadcast.js
More verbose logging for test_dgram_broadcast was added for easier
debugging.
IoT.js-DCO-1.0-Signed-off-by: Piotr Marcinkiewicz p.marcinkiew@samsung.com
> Verbose logging for test_dgram_broadcast

- test/run_pass/test_net_7.js
- TizenRT has a limited number of TCP listener.
- Be able to connect only a specified number of sockets.
> Improve net test for low os (#1192)

- tools/precommit.py
Advance TizenRT to include buildable fstat
Advance libtuv (include fs test fixes for TizenRT)
Tested on Artik053
> Fix fstat on file for TizenRT

- tools/precommit.py
> TizenRT version update

- src/modules/iotjs_module_udp.c
> Enable multicast in UDP module (#1194)

- .travis.yml
IoT.js-DCO-1.0-Signed-off-by: Piotr Marcinkiewicz p.marcinkiew@samsung.com
> Misc target removed from Travis CI

- src/iotjs.c
- src/iotjs_binding.c
- src/iotjs_binding.h
- src/iotjs_binding_helper.c
> Simplify the 'iotjs_val_t' (#1200)

- src/iotjs_env.c
- src/modules/iotjs_module_buffer.c
> Fix defects from static analysis (#1234)

- test/run_pass/test_uart.js
IoT.js-DCO-1.0-Signed-off-by: Marcin Ziombski <m.ziombski@samsung.com>
> Test fixes: Uart description and hardware setup info

- tools/precommit.py
> Advance tizenrt (no significant improvements)

- test/run_pass/test_spi.js
IoT.js-DCO-1.0-Signed-off-by: Marcin Ziombski <m.ziombski@samsung.com>
> Test fixes: SPI description and hardware setup info

- test/run_pass/test_adc.js
- test/testsets.json
> Test fixes: ADC tests documentation

- tools/measure_coverage.sh
IoT.js-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com
> Fix measure_coverage.sh to be able to run check_test.js (#1203)

- src/iotjs_binding.h
- src/modules/iotjs_module_adc.c
- src/modules/iotjs_module_blehcisocket.c
- src/modules/iotjs_module_buffer.c
- src/modules/iotjs_module_buffer.h
- src/modules/iotjs_module_dns.c
- src/modules/iotjs_module_dns.h
- src/modules/iotjs_module_fs.c
- src/modules/iotjs_module_gpio.c
- src/modules/iotjs_module_httpparser.c
- src/modules/iotjs_module_pwm.c
- src/modules/iotjs_module_spi.c
- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_uart.c
- src/modules/iotjs_module_udp.c
- src/platform/linux/iotjs_module_blehcisocket-linux.c
Change 'iotjs_jval_t*' function parameters to 'iotjs_jval_t' under modules directory (part 1). (#1209)
> Change 'iotjs_jval_t*' function parameters (#1209)

- test/run_pass/test_i2c.js
> Test fixes: I2C test documentation

- src/iotjs_binding.c
- src/iotjs_binding.h
- src/iotjs_handlewrap.c
- src/iotjs_reqwrap.c
- src/modules/iotjs_module_https.c
- src/modules/iotjs_module_uart.c
> Changed 'iotjs_jval_create_copied' to 'jerry_acquire_value'. (#1226)

- src/iotjs_binding.c
- src/iotjs_binding.h
- src/iotjs_binding_helper.c
- src/modules/iotjs_module_adc.c
- src/modules/iotjs_module_buffer.c
- src/modules/iotjs_module_fs.c
- src/modules/iotjs_module_gpio.c
- src/modules/iotjs_module_httpparser.c
- src/modules/iotjs_module_https.c
- src/modules/iotjs_module_i2c.c
- src/modules/iotjs_module_process.c
- src/modules/iotjs_module_pwm.c
- src/modules/iotjs_module_spi.c
- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_testdriver.c
- src/modules/iotjs_module_timer.c
- src/modules/iotjs_module_uart.c
- src/modules/iotjs_module_udp.c
- src/platform/linux/iotjs_module_blehcisocket-linux.c
- src/platform/linux/iotjs_module_gpio-linux.c
Removed pointer from function parameter of 'iotjs_jval_get_property' (#1240)
> Removed pointer from function parameter (#1240)

- src/iotjs.c
- src/iotjs_binding.c
- src/iotjs_binding.h
- src/iotjs_binding_helper.c
- src/modules/iotjs_module_adc.c
- src/modules/iotjs_module_blehcisocket.c
- src/modules/iotjs_module_buffer.c
- src/modules/iotjs_module_constants.c
- src/modules/iotjs_module_dns.c
- src/modules/iotjs_module_fs.c
- src/modules/iotjs_module_gpio.c
- src/modules/iotjs_module_httpparser.c
- src/modules/iotjs_module_i2c.c
- src/modules/iotjs_module_process.c
- src/modules/iotjs_module_pwm.c
- src/modules/iotjs_module_spi.c
- src/modules/iotjs_module_stm32f4dis.c
- src/modules/iotjs_module_stm32f4dis.h
- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_timer.c
- src/modules/iotjs_module_uart.c
- src/modules/iotjs_module_udp.c
- src/platform/nuttx/iotjs_module_stm32f4dis-nuttx.c
Removed pointer from function parameter of 'iotjs_jval_set_property_' (#1228)
> Removed pointer from function parameter (#1228)

- src/iotjs_module.c
- src/js/iotjs.js
- src/js/module.js
- variables used in iotjs.js should not be visible from outside
- typo fix
- remove not-used parameter(isMain)
IoT.js-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com
> Fix bugs in module (#1264)

- src/platform/tizen/iotjs_module_gpio-tizen.c
- It's a patch to fix only build break
IoT.js-DCO-1.0-Signed-off-by: Haesik, Jun haesik.jun@samsung.com
> Fix tizen(RPI3) build break (#1269)

- .eslintignore
- .eslintrc.js
- src/js/assert.js
- src/js/buffer.js
- src/js/dgram.js
- src/js/events.js
- src/js/fs.js
- src/js/gpio.js
- src/js/http.js
- src/js/http_client.js
- src/js/http_common.js
- src/js/http_outgoing.js
- src/js/http_server.js
- src/js/https_client.js
- src/js/https_incoming.js
- src/js/iotjs.js
- src/js/module.js
- src/js/net.js
- src/js/pwm.js
- src/js/spi.js
- src/js/stream_writable.js
- src/js/uart.js
- src/js/util.js
apply only rules that are automatically modified.
> Define and apply new eslint rules (#1270)

- src/iotjs.c
- src/iotjs_binding.c
- src/iotjs_binding.h
- src/iotjs_binding_helper.c
- src/iotjs_objectwrap.c
- src/modules/iotjs_module_adc.c
- src/modules/iotjs_module_blehcisocket.c
- src/modules/iotjs_module_buffer.c
- src/modules/iotjs_module_console.c
- src/modules/iotjs_module_dns.c
- src/modules/iotjs_module_fs.c
- src/modules/iotjs_module_gpio.c
- src/modules/iotjs_module_httpparser.c
- src/modules/iotjs_module_https.c
- src/modules/iotjs_module_i2c.c
- src/modules/iotjs_module_process.c
- src/modules/iotjs_module_pwm.c
- src/modules/iotjs_module_spi.c
- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_testdriver.c
- src/modules/iotjs_module_timer.c
- src/modules/iotjs_module_uart.c
- src/modules/iotjs_module_udp.c
- src/platform/linux/iotjs_module_blehcisocket-linux.c
- src/platform/linux/iotjs_module_gpio-linux.c
This PR contains several commits rebased from Samsung/master:
#1250 #1249 #1248 #1243 #1242 #1224
> Removed pointer related changes from Samsung/master

- src/iotjs.c
- src/iotjs_binding.c
- src/iotjs_binding.h
- src/iotjs_binding_helper.c
- src/iotjs_handlewrap.c
- src/iotjs_module.c
- src/iotjs_reqwrap.c
- src/modules/iotjs_module_adc.c
- src/modules/iotjs_module_blehcisocket.c
- src/modules/iotjs_module_buffer.c
- src/modules/iotjs_module_fs.c
- src/modules/iotjs_module_gpio.c
- src/modules/iotjs_module_httpparser.c
- src/modules/iotjs_module_https.c
- src/modules/iotjs_module_i2c.c
- src/modules/iotjs_module_process.c
- src/modules/iotjs_module_pwm.c
- src/modules/iotjs_module_spi.c
- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_testdriver.c
- src/modules/iotjs_module_timer.c
- src/modules/iotjs_module_timer.h
- src/modules/iotjs_module_uart.c
- src/modules/iotjs_module_udp.c
- src/platform/linux/iotjs_module_blehcisocket-linux.c
- src/platform/linux/iotjs_module_gpio-linux.c
- src/platform/nuttx/iotjs_module_stm32f4dis-nuttx.c
> Removed 'iotjs_jval_destroy' (#1253)

- tools/clean.sh
> Add tools/clean.sh script to clean iotjs repository and dependencies.

- tools/precommit.py
> Workaround for failing testsuite on artik053

- src/iotjs_handlewrap.c
- src/iotjs_handlewrap.h
- src/modules/iotjs_module_tcp.c
- src/modules/iotjs_module_timer.c
- src/modules/iotjs_module_uart.c
- src/modules/iotjs_module_udp.c
> Removed 'iotjs_jval_t' pointer from 'iotjs_handlewrap'. (#1265)

- src/platform/linux/iotjs_module_gpio-linux.c
- src/platform/tizen/iotjs_module_gpio-tizen.c
- src/platform/tizenrt/iotjs_module_gpio-tizenrt.c
> Change to IOTJS_ALLOC instead of malloc (#1280)

- src/iotjs_binding.c
IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com
> Remove iotjs_jval_create_raw from the binding layer (#1287)

- src/iotjs_binding.c
- src/iotjs_binding.h
- src/modules/iotjs_module_buffer.c
- src/modules/iotjs_module_fs.c
- src/modules/iotjs_module_httpparser.c
- src/modules/iotjs_module_process.c
- src/modules/iotjs_module_spi.c
Remove excess value acquiring in iotjs_jhandler_return_jval/iotjs_jhandler_throw
IoT.js-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com
> Remove excess value acquiring (#1291)

- samples/light-fade/light-fade.js
- samples/udp-chat/chat.js
Simulates chat bots talking to each other in a local network. The first one starts in server mode, the other connect to it.
Turns LED light on/off at the press of the button with a fade effect using PWM.
> Udp chat #1286, light fade #1283
